language: go
os:
- linux
services:
- docker
go:
- 1.12.x
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- go test -v ./...
branches:
  only:
  - master
deploy:
  provider: script
  script: ./docker.sh
  on:
    branch: master
notifications:
  email: false
